### ISSUE TITLE
[GyroShell BUG]

### ISSUE THREAD

**Issue by horyzen1** [Pdawg-bytes/GyroShell#13]
**Describe the bug**
Taskbar disappears after running then stopping Gyroshell. 

**To Reproduce**
Steps to reproduce the behavior (provide the most specific actions you can):
1. Go to 'visual studio'
2. Click on 'run the program'
3. Stop the program
4. Taskbar disappears

**Expected behavior**
Taskbar should come back after stopping Gyroshell.

**Screenshots**
<img width="1377" alt="Screenshot 2023-04-15 105338" src="https://user-images.githubusercontent.com/94490639/232232229-d654ebce-1699-459c-aa18-5992a5536cdb.png">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - OS Version [22621]
 - GyroShell Version [latest]
 - Architecture [X64]

**Additional context**

**Comment by Pdawg-bytes** [comment]
Hey! Thanks for the bug report. This is fully expected behavior, and GyroShell must be gracefully shut down by right clicking the start menu, scrolling down in the context menu, and then click "Close GyroShell". The reason this happens is because the stop button in Visual Studio force kills GyroShell, not allowing it to complete its shutdown procedure (that does a few things like re enable the regular taskbar.)
